### ISSUE TITLE
App crashing on reboot startup

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/Citadel-Windows#38]
```
2017-05-31 14:11:58.9043 INFO Authenticated user model loading from C:\Program Files\CloudVeil\CloudVeil For Windows\u.dat.
2017-05-31 14:12:00.9163 INFO Attempting authentication via POST to https://technikempire.com/citadel/login
2017-05-31 14:12:01.8223 INFO Filter engine handle opened successfully.
2017-05-31 14:12:01.8223 INFO Failed to delete old installed filter: 2150760451
2017-05-31 14:12:01.8223 ERROR Error during initialization.
2017-05-31 14:12:01.8223 ERROR One or more errors occurred.
2017-05-31 14:12:01.8223 ERROR    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Te.Citadel.CitadelApp.DoBackgroundInit(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
2017-05-31 14:12:01.8223 ERROR Object reference not set to an instance of an object.
2017-05-31 14:12:01.8223 ERROR    at Te.Citadel.UI.Models.AuthenticatedUserModel.<Authenticate>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Te.Citadel.UI.Models.AuthenticatedUserModel.<ReAuthenticate>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Te.Citadel.CitadelApp.<ChallengeUserAuthenticity>d__60.MoveNext()
2017-05-31 14:12:01.8945 INFO Application shutdown detected with code -1.
2017-05-31 14:12:02.0198 ERROR Object reference not set to an instance of an object.
2017-05-31 14:12:02.0198 ERROR    at Te.Citadel.CitadelApp.DoCleanShutdown(Boolean installSafeguards)
```

**Comment by TechnikEmpire** [comment]
Oops this was fixed with #44
